const { database, pubsub, https } = require('firebase-functions')

const { reviseStory } = require('./exports/reviseStory')
const { publishStory } = require('./exports/publishStory')
const { publishNotif } = require('./exports/publishNotif')
const { publishFeed } = require('./exports/publishFeed')
const { emptyTrash } = require('./exports/emptyTrash')
const { incrementView } = require('./exports/incrementView')
const { shortenURL, redirectURL } = require('./exports/shortcutURL')

exports.reviseStory = database.instance('ahs-app').ref('/inputs/{storyID}').onWrite(reviseStory)
exports.publishStory = database.instance('ahs-app').ref('/storys/{storyID}').onWrite(publishStory)
exports.publishNotif = pubsub.schedule('*/5 * * * *').onRun(publishNotif)
exports.publishFeed = pubsub.schedule('0 0 * * *').onRun(publishFeed)
exports.emptyTrash = pubsub.schedule('0 0 * * *').onRun(emptyTrash)
exports.incrementView = https.onCall(incrementView)
exports.shortenURL = https.onRequest(shortenURL)
exports.redirectURL = https.onRequest(redirectURL)
